location_list = ["Santa Clarita, CA",
"New York, NY",
"Forney, TX",
"Albany, GA",
"United States",
"Muskegon, MI",
"Texas, United States",
"Minot, ND",
"Maine, United States",
"Connecticut, United States",
"Atlanta, GA",
"Phoenix, AZ",
"Patchogue, NY",
"New York, United States",
"Richmond, VA",
"New Hampshire, United States",
"San Diego, CA",
"Miami, FL",
"Minneapolis, MN",
"Spokane, WA",
"Puyallup, WA",
"Los Angeles, CA",
"Cincinnati, OH",
"Marietta, GA",
"Chillicothe, OH",
"Roswell, GA",
"Daly City, CA",
"Winnetka, IL",
"California, United States",
"Los Angeles Metropolitan Area",
"Greater Phoenix Area",
"Mineola, NY",
"San Francisco, CA",
"Columbia, PA",
"Alexandria, VA",
"Englewood, CO",
"Chicago, IL",
"Arlington, WA",
"Mesa, AZ",
"Ocala, FL",
"Herndon, VA",
"Henrico, VA",
"Annapolis, MD",
"Sacramento, CA",
"Long Beach, CA",
"Walnut, CA",
"Austin, TX",
"San Gabriel, CA",
"Juneau, AK",
"Manitou Springs, CO",
"Miami-Dade County, FL",
"The Woodlands, TX",
"Nashville, TN",
"San Francisco Bay Area",
"New York City Metropolitan Area",
"Baltimore, MD",
"Charleston, SC",
"Waterloo, IA",
"Logan, UT",
"Allendale, NJ",
"Ames, IA",
"Burbank, CA",
"Newport Beach, CA",
"Brick, NJ",
"Bellaire, TX",
"Seattle, WA",
"Greater Orlando",
"Madison, GA",
"Washington, DC",
"Dallas, TX",
"Fullerton, CA",
"Stratford, CT",
"Greater Houston",
"Boston, MA",
"Columbus, IN",
"Thousand Oaks, CA",
"Byron, IL",
"Anniston, AL",
"St Cloud, FL",
"Abbeville, SC",
"Washington DC-Baltimore Area",
"Orange County, CA",
"Greater Seattle Area",
"Oklahoma City, OK",
"McKinney, TX",
"Raleigh, NC",
"North Canton, OH",
"Las Vegas, NV",
"St Louis, MO",
"Madison, WI",
"Columbia, MO",
"Plano, TX",
"Davenport, IA",
"Mountain View, CA",
"Spring House, PA",
"Cupertino, CA",
"St Petersburg, FL",
"Clearwater, FL",
"Buffalo, NY",
"Tuscaloosa, AL",
"Middleton, MA",
"Sylvania, OH",
"Smyrna, TN",
"Philadelphia, PA",
"Greater Philadelphia",
"Beltsville, MD",
"Ithaca, NY",
"Eldersburg, MD",
"Houston, TX",
"De Forest, WI",
"Dyersville, IA",
"Wellesley, MA",
"West Columbia, SC",
"Wichita, KS",
"Archbold, OH",
"Grand Rapids, MN",
"Milwaukee, WI",
"Brentwood, TN",
"Exeter, NH",
"Orlando, FL",
"Malvern, PA",
"Utica, MI",
"Overland Park, KS",
"Valley Cottage, NY",
"Goshen, NY",
"East Lyme, CT",
"Tampa, FL",
"New London, CT",
"Hudson, OH",
"Providence, RI",
"Largo, FL",
"Mount Juliet, TN",
"La Grange, IL",
"Billerica, MA",
"Nashville Metropolitan Area",
"Conshohocken, PA",
"Frisco, TX",
"Arlington Heights, IL",
"Hamilton, OH",
"Greater Pittsburgh Region",
"Charlottesville, VA",
"Oswego, NY",
"Palm Beach, FL",
"Bradenton, FL",
"Mexico, NY",
"Glastonbury, CT",
"Quantico, VA",
"Queens, NY",
"Sheboygan, WI",
"Randolph, NJ",
"Norwood, MA",
"Farmingdale, NY",
"Augusta, GA",
"West Nyack, NY",
"Norfolk, VA",
"Plattsburgh, NY",
"New Castle, DE",
"Libertyville, IL",
"Brooklyn, NY",
"Greater Milwaukee",
"Bethesda, MD",
"College Park, MD",
"Devon, PA",
"Winter Park, FL",
"Manassas, VA",
"Fulton, NY",
"Somerset, NJ",
"Silverdale, WA",
"Daytona Beach, FL",
"Marshalltown, IA",
"Eden Prairie, MN",
"Columbus, OH",
"Omaha, NE",
"Pensacola, FL",
"Westmont, IL",
"Detroit Metropolitan Area",
"Elgin, TX",
"Old Fort, NC",
"Murray, UT",
"Indianapolis, IN",
"West Valley City, UT",
"Highlands Ranch, CO",
"Waimea, HI",
"Greater Indianapolis",
"Kansas City, KS",
"Sioux City, IA",
"Calabasas, CA",
"University Park, PA",
"Barstow, CA",
"Midland, TX",
"Garner, NC",
"Greater Sacramento",
"Lansing, MI",
"Wilton, CT",
"Minnetonka, MN",
"Georgia, United States",
"Durham, NC",
"Napa, CA",
"White Plains, NY",
"Plainsboro, NJ",
"Woodbury, MN",
"North Miami, FL",
"Lakewood, NJ",
"St Charles, MO",
"Tempe, AZ",
"West Point, VA",
"Lake Charles, LA",
"St Louis, Missouri, United States",
"Lutherville, MD",
"Kansas City, MO",
"Easton, PA",
"Fort Myers, FL",
"Belmont, MA",
"Cambridge, MA",
"Salt Lake City, UT",
"Colorado Springs, CO",
"Fort Worth, TX",
"Gambrills, MD",
"Elmwood Park, IL",
"Montgomery Village, MD",
"Broomfield, CO",
"Longmont, CO",
"Green Forest, AR",
"Rockville, MD",
"Bay City, MI",
"Harvey, LA",
"Short Hills, NJ",
"West Bloomfield Township, MI",
"Natick, MA",
"Greenwich, CT",
"Park Ridge, IL",
"Birmingham, MI",
"Champlin, MN",
"Belmont, CA",
"Roseland, NJ",
"Saginaw, MI",
"Tucson, AZ",
"Alpharetta, GA",
"Wausau, WI",
"Irvine, CA",
"Reston, VA",
"Culver City, CA",
"Birmingham, AL",
"Coppell, TX",
"Longwood, FL",
"Gallup, NM",
"Brighton, MI",
"Dublin, OH",
"Greater Fort Collins Area",
"Winston-Salem, NC",
"Greater Richmond Region",
"Knoxville, TN",
"Bethlehem, PA",
"Scottsdale, AZ",
"Boise, ID",
"Carpentersville, IL",
"Costa Mesa, CA",
"Marion, NC",
"Farmington, CT",
"Greater Chicago Area",
"Delaware Water Gap, PA",
"Woodridge, IL",
"Everett, WA",
"Camden, NJ",
"Waterboro, ME",
"Carlsbad, CA",
"Brooklyn Park, MN",
"Grand Rapids, MI",
"Charlotte, NC",
"Summerville, SC",
"Friendswood, TX",
"Wichita, Kansas Metropolitan Area",
"Ontario, CA",
"Lubbock, TX",
"Lapeer, MI",
"Newark, CA",
"Lexington, SC",
"Virginia, United States",
"Reno, NV",
"West Hollywood, CA",
"Miami-Fort Lauderdale Area",
"New Lenox, IL",
"Hopewell, VA",
"Mesquite, TX",
"Huger, SC",
"Worcester, MA",
"Canton, GA",
"Austin, Texas Metropolitan Area",
"Edwardsville, KS",
"North Wales, PA",
"Atlanta Metropolitan Area",
"Rensselaer, NY",
"San Antonio, TX",
"Hoboken, NJ",
"Kissimmee, FL",
"Ohio, United States",
"Denver, CO",
"Woonsocket, RI",
"San Jose, CA",
"St. Louis County, MO",
"Fremont, OH",
"Fort Wayne, IN",
"Hayward, CA",
"Covington, LA",
"Troy, MI",
"Volusia County, FL",
"Berkeley Heights, NJ",
"Marion County, FL",
"Peoria, IL",
"Columbus, GA",
"Cleveland, OH",
"Florida, United States",
"Maryland, United States",
"Northridge, California, United States",
"Parsippany, NJ",
"Islamorada, FL",
"Grant, IL",
"Hawthorne, CA",
"Hoffman Estates, IL",
"Andover, MA",
"Fort George G. Meade, MD",
"Irving, TX",
"Warren, MA",
"Sunnyvale, CA",
"Fremont, CA",
"Arden Hills, MN",
"Sheridan, WY",
"Downey, CA",
"Jersey City, NJ",
"Kansas City Metropolitan Area",
"Waco, TX",
"Mechanicsville, VA",
"Massachusetts, United States",
"Merrimack, NH",
"Cedar Springs, MI",
"Ketchum, ID",
"Doral, FL",
"Beaverton, OR",
"Lubbock County, TX",
"Leesburg, VA",
"Rock Island, IL",
"South Milwaukee, WI",
"Delaware, United States",
"Santa Clara, CA",
"Goodlettsville, TN",
"Kirkland, WA",
"Chattanooga, TN",
"Jackson, MS",
"Lyon, MI",
"Dallas-Fort Worth Metroplex",
"Tallahassee, FL",
"Lakeland, FL",
"Maple Grove, MN",
"Rochelle, IL",
"Lake Forest, IL",
"Louisville, KY",
"Williamsport, MD",
"Mashantucket, CT",
"Lake County, IL",
"Raleigh-Durham-Chapel Hill Area",
"Plymouth, PA",
"Monterey, CA",
"Medford, MA",
"Aventura, FL",
"Lubbock-Levelland Area",
"Glen Allen, VA",
"Fargo, ND",
"Toledo, OH",
"Springfield, VA",
"Wayzata, MN",
"Hanover, MA",
"Dayton, OH",
"Hillsboro, OR",
"Kansas, United States",
"South Bend, IN",
"Auburn Hills, MI",
"Paramus, NJ",
"St Augustine, FL",
"Pittsburgh, PA",
"Tulsa, OK",
"Langhorne, PA",
"Western Springs, IL",
"Elgin, IL",
"Orange, CA",
"Berkeley, CA",
"Golden, CO",
"Rancho Santa Margarita, CA",
"Santa Ana, CA",
"Round Rock, TX",
"Newark, DE",
"La Verne, CA",
"Little Rock Metropolitan Area",
"Bryn Mawr, PA",
"New Brunswick, NJ",
"Mechanicsburg, PA",
"Butte, MT",
"Juno Beach, FL",
"Grand Rapids Metropolitan Area",
"Swarthmore, PA",
"Los Angeles County, CA",
"Fergus Falls, MN",
"Provo, UT",
"Brunswick, OH",
"Sugar Land, TX",
"Princeton, NJ",
"New Jersey, United States",
"Dedham, MA",
"Claremont, NC",
"King of Prussia, PA",
"South San Francisco, CA",
"Winter Park, CO",
"Austin, MN",
"Bristol, CT",
"Purchase, NY",
"Blue Ash, OH",
"Crawfordsville, IN",
"Edmonds, WA",
"Santa Barbara-Santa Maria Area",
"Sparks, NV",
"Gulf Shores, AL",
"Jacksonville, FL",
"Burton, MI",
"Sheldon, IA",
"Boyertown, PA",
"Oak Brook, IL",
"Lebanon, MO",
"Alabama, United States",
"Denver Metropolitan Area",
"Burlington, MA",
"Charlotte Metro",
"Spanaway, WA",
"Williston, VT",
"Ann Arbor, MI",
"Mount Pleasant, SC",
"Marina del Rey, CA",
"Paris, TX",
"Fillmore, CA",
"Hartford, CT",
"Charleroi, PA",
"Aurora, OH",
"Buckhead, GA",
"Bowling Green, KY",
"Arizona, United States",
"Urbana-Champaign Area",
"Crestview-Fort Walton Beach-Destin Area",
"Thomasville, NC",
"Redmond, WA",
"Grand Prairie, TX",
"Redding, CA",
"Memphis, TN",
"Jean, NV",
"Waukegan, IL",
"Rosemont, IL",
"De Pere, WI",
"Katy, TX",
"Joliet, IL",
"San Antonio, Texas Metropolitan Area",
"Buffalo-Niagara Falls Area",
"Brenham, TX",
"Santa Barbara County, CA",
"Stamford, CT",
"Oakdale, MN",
"Johns Creek, GA",
"Mebane, NC",
"Medford, OR",
"City of Industry, CA",
"San Marcos, CA",
"College Station, TX",
"Aliso Viejo, CA",
"Stafford, TX",
"Myrtle Beach, SC",
"Fort Atkinson, WI",
"Skokie, IL",
"Mandan, ND",
"Elizabethtown, KY",
"Garden City, KS",
"Columbus, Ohio Metropolitan Area",
"Illinois, United States",
"Portland, Oregon Metropolitan Area",
"Westfield, IN",
"Annapolis Junction, MD",
"Fort Lauderdale, FL",
"Waukesha County, WI",
"Lowell, MA",
"Middlesex County, NJ",
"Woodburn, OR",
"Morrisville, PA",
"Charleston, IL",
"Kenosha, WI",
"San Mateo, CA",
"Ayer, MA",
"San Ramon, CA",
"Winn, MI",
"Oakland, CA",
"Montvale, NJ",
"Germantown, TN",
"Bellevue, WA",
"Rochester, NY",
"Mobile Metropolitan Area",
"Las Vegas Metropolitan Area",
"Huntsville-Decatur-Albertville Area",
"Missouri, United States",
"Hampton, VA",
"Suwanee, GA",
"Piscataway, NJ",
"Arlington, VA",
"Decorah, IA",
"St Paul, MN",
"Baytown, TX",
"Torrance, CA",
"Richardson, TX",
"Troy, AL",
"Manhattan Beach, CA",
"Christiana, DE",
"Des Moines Metropolitan Area",
"Colleyville, TX",
"Ravenswood, WV",
"Columbia, South Carolina Metropolitan Area",
"Tallapoosa, GA",
"Pearl River, NY",
"Lyndhurst, VA",
"Fridley, MN",
"Lincoln, Nebraska Metropolitan Area",
"Norcross, GA",
"Honolulu, HI",
"New Orleans, LA",
"Cumming, GA",
"Georgetown, TX",
"St Joseph, MO",
"Marlborough, MA",
"Greater Bangor Area",
"Warwick, RI",
"Silver Spring, MD",
"Farmington Hills, MI",
"Holyoke, MA",
"Port Hope, MI",
"Bolingbrook, IL",
"Greater Boston",
"Vancouver, WA",
"Moab, UT",
"Greater St. Louis",
"Albany, NY",
"Greenwood Village, CO",
"Santa Monica, CA",
"Orange City, FL",
"Fort Mill, SC",
"Davis, CA",
"Duncan, OK",
"Spring, TX",
"Holland, MI",
"Billings, MT",
"St Charles, IL",
"Manhattan, NY",
"Oaks, PA",
"Marion, IA",
"Texas City, TX",
"Fairfax, VA",
"Cerritos, CA",
"Thorofare, NJ",
"Hollister, CA",
"Atlantic City, NJ",
"Springfield, OH",
"El Cajon, CA",
"Green Bay, WI",
"Addison, TX",
"Belton, MO",
"Newtown, CT",
"Ventura, CA",
"Port Arthur, TX",
"Cobb County, GA",
"Selah, WA",
"Basalt, CO",
"Fishers, IN",
"Escondido, CA",
"Edison, NJ",
"New Hyde Park, NY",
"Mossville, IL",
"Lafayette, IN",
"Greensboro, NC",
"Anaheim, CA",
"Little Rock, AR",
"Itasca, IL",
"Camarillo, CA",
"Lancaster, PA",
"Reading, PA",
"Moline, IL",
"San Luis Obispo, CA",
"Simi Valley, CA",
"Hugo, MN",
"Battle Creek, MI",
"Newport News, VA",
"Lawrenceville, GA",
"Monticello, MN",
"Neenah, WI",
"Detroit, MI",
"Greenville, SC",
"Colorado, United States",
"Springfield, PA",
"Edwardsburg, MI",
"Red Bank, NJ",
"Port Austin, MI",
"Rock Springs, WY",
"Foster City, CA",
"Cincinnati Metropolitan Area",
"Boulder, CO",
"Jessup, MD",
"Columbia, SC",
"Westborough, MA",
"Tennessee, United States",
"Fresno, CA",
"Albuquerque, NM",
"Tucker, GA",
"Oswego, IL",
"Merrillville, IN",
"Hilton Head Island, SC",
"Macon, GA",
"Highland, CA",
"West Chester, PA",
"Baton Rouge, LA",
"Orlando, Florida, United States",
"Antioch, IL",
"Basking Ridge, NJ",
"Bentonville, AR",
"McLean, VA",
"Winamac, IN",
"Whately, MA",
"Rogers, AR",
"Greater Chattanooga",
"Frederick County, MD",
"Rosemount, MN",
"Greater Minneapolis-St. Paul Area",
"Bowling Green Metropolitan Area",
"Moss Point, MS",
"Selma, AL",
"North Carolina, United States",
"Sulphur Springs, TX",
"Pasadena, CA",
"San Diego Metropolitan Area",
"Frederick, MD",
"Daleville, VA",
"Hagerstown, MD",
"Riverton, UT",
"Fargo-Moorhead",
"Nampa, ID",
"Metro Jacksonville",
"Oakbrook Terrace, IL",
"Falls Church, VA",
"Summit, NJ",
"Trenton, NJ",
"Newark, NJ",
"Greeley, CO",
"Pomona, CA",
"Hebron, ME",
"Plymouth, MN",
"Hickory, NC",
"Clarksville, TN",
"Newport, AR",
"Iowa, United States",
"Greensboro--Winston-Salem--High Point Area",
"Poway, CA",
"Jerome, ID",
"Maui County, HI",
"Griffin, GA",
"Urbandale, IA",
"New Haven, CT",
"Fort Washington, PA",
"Duluth, GA",
"Kinde, MI",
"Swiftwater, PA",
"Chantilly, VA",
"Downers Grove, IL",
"Aurora, CO",
"Athens, OH",
"Thief River Falls, MN",
"Hermitage, TN",
"Duluth, MN",
"Des Moines, IA",
"Buckeye, AZ",
"Syracuse, NY",
"Home, KS",
"Malibu, CA",
"Albany, New York Metropolitan Area",
"Gainesville, MS",
"Utah, United States",
"Harrisburg, PA",
"Cedar Rapids, IA",
"Brea, CA",
"High Point, NC",
"Essex Junction, VT",
"Greater Idaho Falls",
"Beachwood, OH",
"Eastpointe, MI",
"Wenatchee, WA",
"Hopkinsville, KY",
"Marysville, OH",
"Warrenville, IL",
"Columbia, MD",
"Cary, NC",
"Rothbury, MI",
"McFarland, WI",
"Watsonville, CA",
"New Richmond, WI",
"Wilmington, DE",
"Portsmouth, NH",
"Temple Hills, MD",
"Dearborn, MI",
"Felicity, OH",
"Southfield, MI",
"Waltham, MA",
"Plymouth, WI",
"Norwalk, CA",
"Rancho Cucamonga, CA",
"Las Cruces, NM",
"Novi, MI",
"Mahwah, NJ",
"Lincoln, NE",
"Clayton, NC",
"El Segundo, CA",
"Sabina, OH",
"Hunt Valley, MD",
"Melville, NY",
"Santa Rosa, CA",
"Carson, CA",
"Woburn, MA",
"Casa Grande, AZ",
"Greer, SC",
"Chesterfield, MO",
"La Canada Flintridge, CA",
"Bakersfield, CA",
"Hilton Head Island, South Carolina Area",
"Prairie Village, KS",
"Santa Fe Springs, CA",
"Commerce City, CO",
"Springdale, AR",
"Redwood City, CA",
"West Palm Beach, FL",
"Allentown, PA",
"Rhode Island, United States",
"Suffern, NY",
"Portland, ME",
"Kapolei, HI",
"River Forest, IL",
"El Centro, CA",
"Northville, MI",
"Prescott, AZ",
"El Dorado, AR",
"Green Bay, Wisconsin Metropolitan Area",
"Kalamazoo, MI",
"Morgantown, WV",
"Strasburg, VA",
"Cambridge, MD",
"Jeffersonville, IN",
"Blair, NE",
"Central, IN",
"Mentor, OH",
"Rockford, MI",
"Lawrence, NJ",
"Harmans, MD",
"Mountainside, NJ",
"Portland, OR",
"Bridgewater, NJ",
"Pleasanton, CA",
"Lockport, NY",
"Magnolia, TX",
"Oliver, PA",
"Garland, TX",
"Fort Hood, TX",
"Goodyear, AZ",
"Beloit, WI",
"Stockbridge, GA",
"Madison, IN",
"St Cloud, MN",
"Huntington Beach, CA",
"Glendale, AZ",
"Bothell, WA",
"Michigan City, IN",
"Latin America",
"Danbury, CT",
"Clayton, MO",
"Lemoore, CA",
"Charleston, South Carolina Metropolitan Area",
"Euclid, OH",
"Secaucus, NJ",
"Pontiac, MI",
"Lawrence, KS",
"Elmhurst, IL",
"Ogden, UT",
"Etna, OH",
"Wixom, MI",
"Laramie, WY",
"Vonore, TN",
"Stillwater, MN",
"Towson, MD",
"Taylor, TX",
"Cashton, WI",
"Glendale, CA",
"Milpitas, CA",
"Walton, KY",
"Verona, WI",
"Liberty, MO",
"Plainfield, IN",
"Washington, United States",
"Rehoboth Beach, DE",
"Rochester, New York Metropolitan Area",
"Shaker Heights, OH",
"Miamisburg, OH",
"Humble, TX",
"Windsor, CT",
"Kingwood, WV",
"White Bear Lake, MN",
"Ottawa, IL",
"Evansville, IN",
"Ramsey, NJ",
"Paton, IA",
"Reynoldsburg, OH",
"Grand Junction, CO",
"Wytheville, VA",
"Chesterton, IN",
"Brook Park, OH",
"North Charleston, SC",
"Hartford County, CT",
"Trussville, AL",
"Alameda, CA",
"Southern Pines, NC",
"Albuquerque-Santa Fe Metropolitan Area",
"Michigan, United States",
"La Mesa, CA",
"North Kingstown, RI",
"East Moline, IL",
"Timonium, MD",
"Moses Lake, WA",
"Franklin, WI",
"Odessa, TX",
"Lehi, UT",
"Temecula, CA",
"Mobile, AL",
"Bozeman, MT",
"Providence County, RI",
"Greater Corpus Christi Area",
"Oklahoma City Metropolitan Area",
"Syosset, NY",
"Lihue, HI",
"Westlake Village, CA",
"Morristown, TN",
"Cloquet, MN",
"Livonia, MI",
"Del Mar, CA",
"Lombard, IL",
"Owings, MD",
"Farmingdale, NJ",
"Boca Raton, FL",
"Lynchburg, VA",
"Novato, CA",
"Ahwatukee, AZ",
"Bloomington, IN",
"Inver Grove Heights, MN",
"Draper, UT",
"Lebanon, KY",
"Browns Summit, NC",
"York, PA",
"Lincolnshire, IL",
"Fort Meade, MD",
"Fort Bragg, North Carolina, United States",
"Pennsylvania, United States",
"Morris Plains, NJ",
"Branchburg, NJ",
"North Chicago, IL",
"Batavia, IL",
"Santa Barbara, CA",
"Maitland, FL",
"Bala-Cynwyd, PA",
"Raymond, OH",
"San Jose, California, United States",
"Gardena, CA",
"Tewksbury, MA",
"Roselle, IL",
"Enon, OH",
"Menlo Park, CA",
"Blythe, CA",
"Vermont, United States",
"Buena Park, CA",
"Harvard, IL",
"Carrollton, TX",
"DeKalb, IL",
"Amarillo, TX",
"Fort Belvoir, VA",
"Union, SC",
"Faison, NC",
"Brisbane, CA",
"Frankfort, KY",
"Palo Alto, CA",
"Maple Shade, NJ",
"Emeryville, CA",
"Brownsburg, IN",
"Hockessin, DE",
"Evans, GA",
"Erie-Meadville Area",
"Wyoming, MI",
"Pacifica, CA",
"Melbourne, FL",
"Delmar, MD",
"Jackson, TN",
"Vallejo, CA",
"Annawan, IL",
"Lakehurst, NJ",
"Caldwell, ID",
"Lafayette, Indiana Metropolitan Area",
"Huntsville, AL",
"Warren, NJ",
"Cedar Falls, IA",
"Potomac, MD",
"San Pedro, CA",
"Raritan, NJ",
"Appleton, WI",
"Plover, WI",
"Batesville, IN",
"Loudon, TN",
"Norwich, CT",
"Biloxi, MS",
"Oakland County, MI",
"Warsaw, IN",
"Salamanca, NY",
"Independence, MO",
"Naperville, IL",
"Twin Falls Area",
"Dawsonville, GA",
"Middlebury, VT",
"Wheaton, IL",
"San Anselmo, CA",
"Winchester, OH",
"Plantation, FL",
"Saline, MI",
"Freeport, TX",
"Germantown, MD",
"Oregon, United States",
"Vienna, VA",
"New Berlin, WI",
"Stockton, CA",
"Olympia, WA",
"Murfreesboro, TN",
"Piedmont, SC",
"Hudson, FL",
"Sun Valley, CA",
"Chandler, AZ",
"Ridgefield, CT",
"Plymouth, MA",
"Georgetown, DE",
"Gardner, KS",
"Penns Grove, NJ",
"Burlingame, CA",
"Whiting, WI",
"Walnut Creek, CA",
"Tukwila, WA",
"Henderson, NV",
"Indianapolis, Indiana, United States",
"Rancho Cordova, CA",
"Calhoun, GA",
"Screven, GA",
"Woodbridge, NJ",
"Charles City, IA",
"Fairburn, GA",
"Plymouth, MI",
"Sharonville, OH",
"Manhasset, NY",
"Vernon Hills, IL",
"Elkhart, IN",
"Metairie, LA",
"Federal Way, WA",
"Elk Grove, CA",
"Capitola, CA",
"Warrenton, MO",
"Corpus Christi, TX",
"Wilmette, IL",
"Robstown, TX",
"Fredericksburg, VA",
"Lynbrook, NY",
"Glenview, IL",
"Iselin, NJ",
"Lake Mary, FL",
"South Carolina, United States",
"Traverse City, MI",
"Collinsville, AL",
"Danville, IL",
"Richmond Heights, MO",
"Ludlow, MA",
"Saddle River, NJ",
"Smackover, AR",
"Media, PA",
"Lewisville, TX",
"Marion, OH",
"Buford, GA",
"Dickinson, ND",
"Des Plaines, IL",
"Crete, NE",
"Kermit, TX",
"Shakopee, MN",
"Deer Park, TX",
"Greenwood, NE",
"Hampton, GA",
"Duarte, CA",
"Homer Glen, IL",
"Rocky Mount, NC",
"Miami Lakes, FL",
"Tamaqua, PA",
"Arkansas, United States",
"Alsip, IL",
"Inglewood, CA",
"North Andover, MA",
"National City, CA",
"Garden Grove, CA",
"Shawnee County, KS",
"Lexington, NC",
"Buena Vista, VA",
"Wilson, NC",
"Aurora, IL",
"Gainesville, FL",
"Kennesaw, GA",
"Anchorage, AK",
"Louisiana, United States",
"Chino, CA",
"Gilbert, PA",
"Fort Collins, CO",
"Mountain Pass, CA",
"Bellevue, OH",
"Eaton, OH",
"Bement, IL",
"Avon Lake, OH",
"Longview, WA",
"Triangle, NC",
"Wallingford, CT",
"Oak Ridge, TN",
"Grand Island, NE",
"Richland, WA",
"National, MD",
"Fishersville, VA",
"Eutaw, AL",
"Bartlesville, OK",
"Stockton, IL",
"Westwood, MA",
"Oklahoma, United States",
"Mississippi, United States",
"Dover, NJ",
"Pensacola Metropolitan Area",
"Chicopee, MA",
"Fayetteville, GA",
"Victorville, CA",
"East Norriton, PA",
"Meridian, ID",
"Sioux Falls, SD",
"Denver, NC",
"Charleston, WV",
"Jefferson City, MO",
"Thornton, CO",
"Roseville, CA",
"Monrovia, CA",
"Orangeburg, SC",
"Yountville, CA",
"Lenoir, NC",
"Siloam Springs, AR",
"Holmdel, NJ",
"Bronx, NY",
"Urbana, IL",
"Youngstown, OH",
"Lake Havasu City, AZ",
"West Melbourne, FL",
"Denison, TX",
"Reynolds, GA",
"Portage, MI",
"Ashtabula, OH",
"Richlands, VA",
"Fostoria, OH",
"Athens, GA",
"Pompano Beach, FL",
"San Francisco County, CA",
"Avondale, LA",
"Edina, MN",
"Dallas County, TX",
"San Dimas, CA",
"McCamey, TX",
"Yuba City, CA",
"Pueblo, CO",
"Kentucky, United States",
"Laguna Hills, CA",
"Pierre, SD",
"Salem, OR",
"Fort Walton Beach, FL",
"San Diego County, CA",
"Coopersburg, PA",
"Rome, NY",
"Roanoke, VA",
"Lancaster, SC",
"Cortlandt Manor, NY",
"Montgomery, AL",
"Greenville, NC",
"Wilmington, NC",
"Sun City, AZ",
"Goldsboro, NC",
"Sun City West, AZ",
"Chelmsford, MA",
"Lakeside, AZ",
"Allen, TX",
"Orange, CT",
"Binghamton, NY",
"Augusta, ME",
"Altoona, PA",
"Alliance, OH",
"Campbell, CA",
"Tustin, CA",
"Gadsden, AL",
"Alachua, FL",
"Leavenworth, KS",
"Alhambra, CA",
"Dulles, VA",
"Windsor, CO",
"Washington, UT",
"Rolling Meadows, IL",
"Santa Fe, NM",
"Dover, DE",
"Cranford, NJ",
"Calera, AL",
"Avon, CT",
"Iowa City, IA",
"Weirton, WV",
"Grand Blanc, MI",
"Santa Clarita, California, United States",
"Sterling Heights, MI",
"Richmond, CA",
"Vestal, NY",
"Leechburg, PA",
"Dalton, GA",
"Lansing, IL",
"Northbrook, IL",
"Riverdale, GA",
"Hurricane, WV",
"Chippewa Falls, WI",
"Denville, NJ",
"Cheyenne, WY",
"Bismarck, ND",
"West Point, MS",
"Boonton, NJ",
"Lake Forest, CA",
"United, PA",
"San Leandro, CA",
"Bloomington, MN",
"Middletown, DE",
"Renton, WA",
"Hernando, MS",
"Ephrata, PA",
"Chambersburg, PA",
"Amherst, NY",
"Greater Los Angeles, CA",
"Encinitas, CA",
"Milbank, SD",
"Cherry Hill, NJ",
"Anacortes, WA",
"Carson City, NV",
"McComb, MS",
"Crawford, TX",
"Bedford, MA",
"Freedom, PA",
"Gardner, MA",
"Erie, PA",
"Portsmouth, OH",
"Pikeville, KY",
"Roseville, MN",
"Russellville, AR",
"Alpena, MI",
"Coral Gables, FL",
"Petersburg, VA",
"Springfield, OR",
"Erlanger, KY",
"Greater Tampa Bay Area",
"Port Huron, MI",
"Mount Laurel, NJ",
"Jamaica, NY",
"North Dakota, United States",
"Eugene, OR",
"Alameda County, CA",
"Mission, TX",
"Marlton, NJ",
"Tigard, OR",
"Vashon, WA",
"Woodland, CA",
"Greater Macon",
"Carmel, IN",
"Lexington, KY",
"Brentwood, CA",
"La Marque, TX",
"Moscow, ID",
"NAMER",
"Denton, TX",
"Levittown, NY",
"SeaTac, WA",
"Burnsville, MN",
"Midland-Odessa Area",
"Narberth, PA",
"Webster City, IA",
"Union City, CA",
"India",
"Livermore, CA",
"Bloomfield Hills, MI",
"Peoria, AZ",
"St Johns, MI",
"Bishopville, SC",
"Cypress, CA",
"Wheeling, WV",
"Clinton, NJ",
"Bedford Heights, OH",
"Chesterfield, VA",
"Wayne, NJ",
"Tracy, CA",
"Issaquah, WA",
"Palestine, TX",
"Scranton, PA",
"Seaside, OR",
"Lynnwood, WA",
"Springfield, MO",
"Moncks Corner, SC",
"Petaluma, CA",
"North Reading, MA",
"Hilliard, OH",
"San Mateo County, CA",
"Springfield, IL",
"Sedona, AZ",
"Red Wing, MN",
"American Fork, UT",
"Nolanville, TX",
"La Jolla, California, United States",
"Illinois City, IL",
"Mansfield, MA",
"Menomonee Falls, WI",
"Goleta, CA",
"Huntington, WV",
"El Paso, TX",
"Lacey, WA",
"Minnesota, United States",
"Kent, WA",
"White Marsh Station, MD",
"Sumner, WA",
"Hanahan, SC",
"Grass Valley, CA",
"Morgan Hill, CA",
"Chester County, PA",
"Greater Yuma, AZ Area",
"Greater New Orleans Region",
"Napa County, CA",
"Pooler, GA",
"St Louis Park, MN",
"Spokane-Coeur d'Alene Area",
"Montpelier, VT",
"Concord, NC",
"Acton, MA",
"Beverly Hills, CA",
"Hanford, CA",
"Rutherford, NJ",
"San Bernardino, CA",
"Oxnard, CA",
"Winnemucca, NV",
"Dobson, NC",
"Brookline, MA",
"Rowland Heights, CA",
"Westwood, CA",
"Rocklin, CA",
"Palm Harbor, FL",
"Newburgh, IN",
"Franklin, TN",
"Signal Hill, CA",
"Byhalia, MS",
"Corvallis, OR",
"Laurel, MS",
"Conyers, GA",
"Morton Grove, IL",
"Centennial, CO",
"Aloha, OR",
"Nevada, United States",
"Ellensburg, WA",
"Tolleson, AZ",
"Riverside, CA",
"Framingham, MA",
"Fountain Valley, CA",
"Aiea, HI",
"League City, TX",
"Scotts Valley, CA",
"Edwardsville, IL",
"Bal Harbour, FL",
"Portland, TN",
"Alexandria, LA",
"Van Buren, AR",
"Destin, FL",
"Meridian, MS",
"Killeen, TX",
"Morris, IL",
"Clifton Park, NY",
"Washington, PA",
"Stanford, CA",
"Seymour, IN",
"Grand Forks, ND",
"Groveport, OH",
"Montgomery, NY",
"Beech Grove, IN",
"Salt Lake City Metropolitan Area",
"Paramount, CA",
"Holdrege, NE",
"Wyandotte, MI",
"Lenexa, KS",
"Mundelein, IL",
"Hicksville, NY",
"Sarasota, FL",
"Sacramento County, CA",
"Edmond, OK",
"Lebanon, IN",
"Mansfield, TX",
"Wesley Chapel, FL",
"Knightdale, NC",
"Twinsburg, OH",
"Collinsville, IL",
"Hanover, MD",
"Ballwin, MO",
"St George, UT",
"Salem, MA",
"Harbeson, DE",
"Salisbury, MD",
"Kernersville, NC",
"Massapequa, NY",
"Schaumburg, IL",
"Muskogee, OK",
"Waterbury, CT",
"Fort Smith, AR",
"Wood River, IL",
"Grandville, MI",
"Kingsport, TN",
"Santa Maria, CA",
"Dania, FL",
"Livingston, MT",
"Surry, VA",
"San Clemente, CA",
"North Myrtle Beach, SC",
"Danvers, MA",
"Corydon, IA",
"Gallatin, TN",
"Smyrna, GA",
"North Little Rock, AR",
"Escanaba, MI",
"Guilderland, NY",
"Florence, SC",
"Fontana, CA",
"Huntsville, TX",
"Fremont, NE",
"Gillette, WY",
"Chestnut Ridge, NY",
"Hillsboro, TX",
"Union County, NJ",
"Ferndale, WA",
"Hudson County, NJ",
"Topeka, KS",
"Cranberry Township, PA",
"Suffolk City County, VA",
"Redlands, CA",
"Fishkill, NY",
"Hopland, CA",
"Mounds View, MN",
"West Sacramento, CA",
"Wyoming, MN",
"Rock Hill, SC",
"Tooele, UT",
"Wilton, NY",
"Canton, MA",
"Abingdon, VA",
"Williamsburg, VA",
"Spartanburg, SC",
"Arlington, TX",
"Caddo Mills, TX",
"Hoover, AL",
"North Bergen, NJ",
"Mooresville, NC",
"Passaic, NJ",
"Appomattox, VA",
"Goodland, KS",
"Berwyn, PA",
"Sanborn, NY",
"Fenton, MO",
"Hermitage, PA",
"Burlington, WA",
"Sandy, UT",
"Grove City, OH",
"Wood Dale, IL",
"Stevens Point, WI",
"Lawton Area",
"Rutland, VT",
"Gonzales, LA",
"Spanish Fort, AL",
"East Greenbush, NY",
"Amsterdam, NY",
"Schenectady, NY",
"Aurora, Colorado, United States",
"Middleburg Heights, OH",
"Huntington, NY",
"Port Orange, FL",
"Cocoa, FL",
"Pendleton, SC",
"Ballinger, TX",
"Martinsville, VA",
"Rochester, MN",
"Burleson, TX",
"Newark, TX",
"Pineville, NC",
"Barrington, IL",
"Mahopac, NY",
"Riverside, NJ",
"Biddeford, ME",
"Florence, KY",
"Ashland, MT",
"Wappingers Falls, NY",
"Ponchatoula, LA",
"Ajo, AZ",
"Anderson, IN",
"Kingsford, MI",
"New York, New York, United States",
"Palm Beach Gardens, FL",
"Greater Cleveland",
"Ossining, NY",
"Berlin, WI",
"Winchester, VA",
"Gaithersburg, MD",
"Cadillac, MI",
"Pittston, PA",
"South Hackensack, NJ",
"Cleveland, GA",
"Bergenfield, NJ",
"Salem, NC",
"Richland, SC",
"Dearborn Heights, MI",
"Farmers Branch, TX",
"Glen Burnie, MD",
"Cleveland, MS",
"Niles, OH",
"Bristol County, MA",
"Roseville, MI",
"Boone, NC",
"Batavia, OH",
"Idaho Falls, ID",
"O'Fallon, MO",
"Burlington, VT",
"Johnston, IA",
"Great Falls, MT",
"Naples, FL",
"Arlington, MA",
"Hudson, WI",
"Lexington, MA",
"Terre Haute, IN",
"Hamilton County, OH",
"Jacksonville, GA",
"Disputanta, VA",
"Braselton, GA",
"Sanford, FL",
"Apex, NC",
"Immokalee, FL",
"St Helena, CA",
"Rye Brook, NY",
"Montana, United States",
"Bergen County, NJ",
"West Chicago, IL",
"South Dakota, United States",
"Elmira-Corning Area",
"Sturgeon Bay, WI",
"Lynn, MA",
"Riviera Beach, FL",
"Finney County, KS",
"Arkadelphia, AR",
"Plaquemine, LA",
"Layton, UT",
"Lewiston, ME",
"McAllen, TX",
"West Long Branch, NJ",
"Scottsbluff, NE",
"Bristol, TN",
"Oregon City, OR",
"Cuyahoga Falls, OH",
"Anoka, MN",
"Addison, IL",
"Janesville, WI",
"Passaic County, NJ",
"Council Bluffs, IA",
"Westbrook, ME",
"Essex County, NJ",
"Kearney, NE",
"Morehead City, NC",
"Kiowa, CO",
"Glendale Heights, IL",
"Monroe, LA",
"Fayetteville, AR",
"West Lafayette, IN",
"Montgomeryville, PA",
"Vacaville, CA",
"Schererville, IN",
"New Braunfels, TX",
"Blue Springs, MO",
"Longview, TX",
"Warner Robins, GA",
"East Peoria, IL",
"Haslet, TX",
"St Clairsville, OH",
"Montclair, NJ",
"Galion, OH",
"Temple Terrace, FL",
"Manalapan, NJ",
"Wauwatosa, WI",
"Gurnee, IL",
"Carlisle, PA",
"Waterford, CT",
"Avon, MA",
"Modesto, CA",
"Jurupa Valley, CA",
"Romulus, MI",
"Orleans, IN",
"Los Angeles, California, United States",
"Virginia Beach, VA",
"Beavercreek, OH",
"Cape Girardeau, MO",
"Leesburg, GA",
"Horsham, PA",
"Manchester, NH",
"Aiken, SC",
"Lone Tree, CO",
"Batavia, NY",
"Northlake, TX",
"Valdosta, GA",
"Mount Prospect, IL",
"Sayreville, NJ",
"Malden, MA",
"Ashburn, VA",
"Norwood, OH",
"Niceville, FL",
"Boulder City, NV",
"Midland, MI",
"Miami Beach, FL",
"Fort Dodge, IA",
"Lakewood, CO",
"Geneva, NY",
"Maumee, OH",
"Staunton, VA",
"Butler, NJ",
"Pembroke Pines, FL",
"Nebraska, United States",
"Los Altos, CA",
"Powell, TN",
"Carrollton, GA",
"Sebastopol, CA",
"Bloomington, CA",
"Annandale, VA",
"Cashmere, WA",
"Nashua, NH",
"Auburn, WA",
"Oak Park, IL",
"Hamburg, NY",
"Bethany, MO",
"Southlake, TX",
"Mt. Joy, PA",
"Theodore, AL",
"Boise Metropolitan Area",
"South Jordan, UT",
"Taunton, MA",
"Lees Summit, MO",
"Kailua-Kona, HI",
"McIntosh, AL",
"Chula Vista, CA",
"Cypress, TX",
"Gilbert, AZ",
"Lakewood Ranch, FL",
"Romeoville, IL",
"New Albany, OH",
"New Bedford, MA",
"Indiana, United States",
"Miramar, FL",
"Forked River, NJ",
"Sausalito, CA",
"Riverside County, CA",
"Arvada, CO",
"Port Angeles, WA",
"Allegan, MI",
"Madera, CA",
"Vineland, NJ",
"Davidson, NC",
"Staten Island, NY",
"Windsor, CA",
"Newberg, OR",
"Milwaukee County, WI",
"Chatham County, NC",
"Green Valley, AZ",
"Tacoma, WA",
"Arcadia, CA",
"Pullman, WA",
"Hartland, WI",
"Rosemead, CA",
"Wyomissing, PA",
"Alanson, MI",
"Brockton, MA",
"Coplay, PA",
"Meadville, PA",
"Farragut, TN",
"Beverly, MA",
"Sandpoint, ID",
"North Las Vegas, NV",
"Locust Valley, NY",
"West Hempstead, NY",
"Warminster, PA",
"Montgomery, OH",
"Middletown, OH",
"Tonganoxie, KS",
"Shelby Township, MI",
"Bellingham, WA",
"Boardman, OR",
"Clearfield, UT",
"Laguna Beach, CA",
"Absecon, NJ",
"Post Falls, ID",
"Asheville, NC",
"Fleetwood, PA",
"Worland, WY",
"Quincy, MA",
"Sitka, AK",
"Bryan, OH",
"Westfield, PA",
"Fairfield, CA",
"Ridgefield Park, NJ",
"Hood River, OR",
"Dunwoody, GA",
"Bowling Green, OH",
"New Ulm, MN",
"Orland Park, IL",
"Carmel, CA",
"West Chester, OH",
"Monroe, WA",
"Hallandale Beach, FL",
"Pasadena, TX",
"Hackettstown, NJ",
"Elizabeth, NJ",
"Hawaii, United States",
"Mendota Heights, MN",
"Breckenridge, CO",
"Middletown, PA",
"Clarksburg, MD",
"Ocean View, DE",
"Weymouth, MA",
"Ala Moana, HI",
"Rialto, CA",
"Westlake, OH",
"Hollywood, MD",
"Woodside, CA",
"Oshkosh, WI",
"Destrehan, LA",
"Kekaha, HI",
"Daggett, CA",
"Suffolk, VA",
"Chestnut Hill, MA",
"Lavonia, GA",
"Union Gap, WA",
"Elk River, MN",
"Randolph, MA",
"Harrisonburg-Staunton-Waynesboro Area",
"Lanham, MD",
"Westminster, CO",
"Dayton, VA",
"Canada, NC",
"Portsmouth, VA",
"Poplar Bluff, MO",
"Mount Horeb, WI",
"Pinellas Park, FL",
"Cape Coral, FL",
"Owosso, MI",
"Mountain Brook, AL",
"Blandon, PA",
"Pickwick Dam, TN",
"Henderson, NC",
"Skaneateles, NY",
"Bordentown, NJ",
"Rahway, NJ",
"Kihei, HI",
"Greater Rockford Area",
"Pixley, CA",
"Lexington County, SC",
"Andrews AFB, MD",
"Darien, CT",
"Branchville, NJ",
"Wentzville, MO",
"Stilwell, OK",
"Wisconsin Rapids, WI",
"East Orange, NJ",
"McKees Rocks, PA",
"Lutz, FL",
"Paragould, AR",
"Douglasville, GA",
"Canby, OR",
"Huntersville, NC",
"Southaven, MS",
"Lowell, AR",
"West Des Moines, IA",
"Ypsilanti, MI",
"Iva, SC",
"Angleton, TX",
"Mount Pleasant, WI",
"Laurel, MD",
"Dayton, TN",
"Sunfish Lake, MN",
"Seabrook, NH",
"Merritt Island, FL",
"Spokane Valley, WA",
"Ellicott City, MD",
"Boardman, OH",
"Westminster, CA",
"Kenedy, TX",
"Missoula, MT",
"China Lake, CA",
"Luray, VA",
"Peru, IN",
"Abilene, TX",
"Yuma, AZ",
"Yorktown Heights, NY",
"Wichita Falls, TX",
"Rocky Mount, VA",
"Put-in-Bay Township, OH",
"Azusa, CA",
"South Brunswick, NJ",
"Redondo Beach, CA",
"Saddle Brook, NJ",
"Rapid City, SD",
"El Cerrito, CA",
"Liberty Township, OH",
"Evergreen, CO",
"Sturbridge, MA",
"New Milford, CT",
"Cass, WV",
"North Royalton, OH",
"Fairless Hills, PA",
"Holly Springs, NC",
"Kohala, HI",
"Gig Harbor, WA",
"Mason City, IA",
"Covina, CA",
"Auburn, ME",
"Rigby, ID",
"Paso Robles, CA",
"Walnut Park, CA",
"Yorktown, NY",
"Greater Reno Area",
"Laguna Niguel, CA",
"Tupelo, MS",
"Moorhead, MN",
"Hollywood, FL",
"Isanti, MN",
"Greendale, IN",
"River Grove, IL",
"New Fairfield, CT",
"Armonk, NY",
"Morrisville, NC",
"Selinsgrove, PA",
"Satellite Beach, FL",
"Maywood, IL",
"Fairview Heights, IL",
"Warren, MI",
"Brecksville, OH",
"Lee, MA",
"Hartsville, SC",
"Eagle, ID",
"Avon, NY",
"Los Alamitos, CA",
"South San Gabriel, CA",
"Philomath, OR",
"North Haven, CT",
"Florissant, MO",
"Manchester, CT",
"Jupiter, FL",
"Folsom, CA",
"Jacksonville, NC",
"Dubuque, IA",
"Carrboro, NC",
"Dyer, IN",
"Hamden, CT",
"Olive Branch, MS",
"Watertown, SD",
"Bound Brook, NJ",
"St Petersburg, Florida, United States",
"Weston, FL",
"Greenbrier, AR",
"Corte Madera, CA",
"Savannah, GA",
"Medford, NY",
"Denison, IA",
"Emmett, ID",
"Chesapeake, VA",
"Capitol Heights, MD",
"Emlenton, PA",
"Mount Clemens, MI",
"Burlington, WI",
"Sparta, TN",
"Piqua, OH",
"Darlington, SC",
"Hamlin, WV",
"Centerville, TN",
"Low Moor, IA",
"Elk Horn, IA",
"Bibb Mill, AL",
"Dublin, GA",
"Kimballton, IA",
"Wildomar, CA",
"Madison, AL",
"Mount Hope, OH",
"Troutdale, OR",
"Ladson, SC",
"Dublin, CA",
"Swedesboro, NJ",
"West Babylon, NY",
"St. Louis City County, MO",
"Port Allen, LA",
"Franklin, MA",
"Forsyth, GA",
"Bensalem, PA",
"Lancaster, TX",
"Cowpens, SC",
"Scarborough, ME",
"Panama City, FL",
"Danville, VA",
"England, AR",
"Kings Park, NY",
"Johnston, RI",
"Haskell, TX",
"Lisle, IL",
"Lithia Springs, GA",
"Waukesha, WI",
"Buras, LA",
"Baldwinville, MA",
"Rolla, MO",
"Egg Harbor, NJ",
"Pelham, AL",
"Middle, NJ",
"Cleveland, TN",
"Penn Hills, PA",
"Smithville, TN",
"McMinnville, TN",
"Milton, FL",
"Slidell, LA",
"Sidney, OH",
"Philadelphia, MS",
"Mount Sterling, KY",
"Owatonna, MN",
"Laredo, TX",
"Brownsville, TX",
"Glenville, WV",
"Richmond, IN",
"Bedminster, NJ",
"Dimondale, MI",
"Kirtland Air Force Base, NM",
"Santa Clara County, CA",
"Bonita Springs, FL",
"Deerfield, IL",
"Decatur, GA",
"Voorhees, NJ",
"Le Mars, IA",
"Pocatello, ID",
"Windsor, WI",
"Champaign, IL",
"Blacksburg, VA",
"La Porte, TX",
"State College, PA",
"Page, AZ",
"Visalia, CA",
"Beaumont, TX",
"Luling, LA",
"Elwyn, PA",
"Buda, TX",
"West Reading, PA",
"Hauppauge, NY",
"Hawley, MN",
"Palm Bay, FL",
"Muncie, IN",
"Phoenixville, PA",
"Concord, CA",
"Lima, OH",
"Dallas, Texas, United States",
"Lake Buena Vista, FL",
"Williamson County, TX",
"Greenwood, IN",
"Bridgeville, PA",
"Westlake, TX",
"Mesquite, Texas, United States",
"Mitchellville, MD",
"Bloomington–Normal, IL",
"LaPlace, LA",
"Stuarts Draft, VA",
"Somerville, MA",
"Wisconsin Dells, WI",
"Wake Forest, NC",
"Hephzibah, GA",
"Morrison, TN",
"Gastonia, NC",
"Walbridge, OH",
"Newburgh, NY",
"Corona, CA",
"Lebanon, TN",
"Orange, TX",
"Mansfield, OH",
"Lafayette, LA",
"Littleton, CO",
"Beaufort, SC",
"Kenton, OH",
"Parsons, KS",
"Supply, NC",
"Cheshire, CT",
"Marengo, IL",
"Okmulgee, OK",
"Clearwater, Florida, United States",
"Stillwater, OK",
"Independence, OH",
"Middletown, IA",
"Winona, MN",
"Woodlyn, PA",
"Langston, OK",
"Perryton, TX",
"DeSoto, TX",
"Surprise, AZ",
"Irvine, California, United States",
"Clinton Township, MI",
"Clarkston, MI",
"McCook, IL",
"Stateline, NV",
"Middleton, ID",
"Leawood, KS",
"Terrell, TX",
"Hialeah, FL",
"Lorain, OH",
"Collegeville, PA",
"Leland, NC",
"Hobart, IN",
"Marinette, WI",
"Hanover Park, IL",
"Halethorpe, MD",
"Charleston, South Carolina, United States",
"North Bronx, NY",
"Feasterville, PA",
"Westford, MA",
"Springfield, MA",
"Danville, PA",
"Jackson County, MO",
"Germany",
"Maryville, TN",
"Moonachie, NJ",
"Riverdale, MD",
"Gresham, OR",
"Silverton, OR",
"Needham, MA",
"Milton, MA",
"Winchester, MA",
"Ocoee, FL",
"Carlsbad, NM",
"Pine Bluff, AR",
"Flowery Branch, GA",
"Lebanon, NH",
"Kenner, LA",
"Fayetteville, NC",
"Cleburne, TX",
"Stephenville, TX",
"Homedale, ID",
"Flint, MI",
"Gaffney, SC",
"District of Columbia, United States",
"Channahon, IL",
"Steamboat Springs, CO",
"Troy, NY",
"Stoneham, MA",
"Shippensburg, PA",
"Lakeville, MN",
"Pryor, OK",
"Flowood, MS",
"Aledo, TX",
"Johnstown, NY",
"Three Bridges, NJ",
"Ellettsville, IN",
"Geneva, AL",
"Midlothian, TX",
"Bend, OR",
"Peabody, MA",
"Pampa, TX",
"Kohler, WI",
"Dodge Center, MN",
"Warrendale, PA",
"Harahan, LA",
"Monroeville, PA",
"Front Royal, VA",
"Cleveland Heights, OH",
"Ware, MA",
"Gypsum, CO",
"Mauldin, SC",
"Deerfield Beach, FL",
"Jal, NM",
"Chevy Chase, MD",
"Port Charlotte, FL",
"Willard, OH",
"Ironwood, MI",
"Havertown, PA",
"Salmon Creek, WA",
"Parkersburg, WV",
"Decatur, IL",
"Bourne, MA",
"Somerset County, NJ",
"Freehold, NJ",
"Culpeper, VA",
"Seguin, TX",
"Garciasville, TX",
"South Pasadena, CA",
"Concord, NH",
"Temple, TX",
"Carol Stream, IL",
"North Hatfield, MA",
"Caro, MI",
"Arden, NC",
"Middleton, WI",
"Banner Elk, NC",
"Burlington, NC",
"Booneville, MS",
"Apopka, FL",
"Owings Mills, MD",
"Sumter, SC",
"Coeur d'Alene, ID",
"Yarmouth, MA",
"Verona, PA",
"Agoura Hills, CA",
"Yankton, SD",
"Preston, CT",
"Niles, MI",
"Salem, NJ",
"Riverhead, NY",
"McDonough, GA",
"Conroe, TX",
"Delray Beach, FL",
"Muscatine, IA",
"Austell, GA",
"East Brunswick, NJ",
"Okemos, MI",
"Grantsville, UT",
"Mosinee, WI",
"Hackleburg, AL",
"Akron, OH",
"West McLean, VA",
"Harrold, SD",
"White Pine, TN",
"Franklin, NH",
"Liverpool, NY",
"Los Osos, CA",
"Woodcliff Lake, NJ",
"Williston, ND",
"Decatur, AL",
"Warsaw, VA",
"Lemont, IL",
"Newtown Square, PA",
"Camelback, California, United States",
"Chapel Hill, NC",
"Olathe, KS",
"Gainesville, VA",
"Hobbs, NM",
"Neptune, NJ",
"Derwood, MD",
"Chester, PA",
"Harrison, MI",
"West Henrietta, NY",
"Sturtevant, WI",
"Tulalip, WA",
"Chesterfield, MI",
"Faribault, MN",
"Westfield, MA",
"Midwest City, OK",
"Hixson, TN",
"Lakeville, MA",
"Hurst, TX",
"Tualatin, OR",
"Pickerington, OH",
"Fairfield, CT",
"Pascagoula, MS",
"Sarasota County, FL",
"Valley City, OH",
"Bennington, VT",
"Greater Birmingham, Alabama Area",
"Mount Vernon, OH",
"Tomah, WI",
"Van Wert, OH",
"Brandon, FL",
"Vernon, WI",
"Hilton, NY",
"Reedley, CA",
"Morris County, NJ",
"Pasadena, MD",
"Wethersfield, CT",
"Elwood, IL",
"Short Pump, VA",
"Springfield-Branson, Missouri Area",
"East Palo Alto, CA",
"Greenville, TX",
"Shorewood, IL",
"Kearny, NJ",
"Pawtucket, RI",
"Oldsmar, FL",
"Norfolk, NE",
"Claremont, NH",
"Aberdeen, MD",
"Vista, CA",
"Sun City Center, FL",
"Crystal Lake, IL",
"East Grand Forks, MN",
"Shelby, OH",
"Hesston, KS",
"Englewood Cliffs, NJ",
"Mecklenburg County, NC",
"Residence Park, OH",
"Greater Lansing",
"Drums, PA",
"West Jordan, UT",
"Arabi, LA",
"Flemington, NJ",
"Lincoln Park, NJ",
"Foxborough (Foxboro), MA",
"Sterling Wood, TX",
"Davie, FL",
"Scott AFB, IL",
"Murrieta, CA",
"Northfield, IL",
"Kaukauna, WI",
"Capistrano Beach, CA",
"Paterson, NJ",
"Jensen Beach, FL",
"Glenpool, OK",
"Ocean, NJ",
"Shreveport, LA",
"O'Fallon, IL",
"Toppenish, WA",
"Coconut Creek, FL",
"Los Alamos, NM",
"Groton, CT",
"South Attleboro, MA",
"Pittsburg, KS",
"Palmer, MA",
"Dickson, TN",
"North Brunswick, NJ",
"Somerset, KY",
"Huntington Station, NY",
"Cayce, SC",
"Attleboro, MA",
"North Richland Hills, TX",
"East Rutherford, NJ",
"Gloucester, MA",
"Wasilla, AK",
"Covington, KY",
"Haverhill, MA",
"Northampton, MA",
"Huntington Park, CA",
"Lynwood, CA",
"Waveland, MS",
"Livingston, NJ",
"Pewaukee, WI",
"Nebraska, IA",
"Wyoming, United States",
"Bridgeton, MO",
"Greater Madison Area",
"Round Lake, IL",
"Occoquan, VA",
"Gap, PA",
"Progreso, TX",
"Yukon, OK",
"Lexington Park, MD",
"Old Greenwich, CT",
"Hillsborough, NC",
"Granbury, TX",
"Elyria, OH",
"Park Forest, IL",
"King George, VA",
"Coral Springs, FL",
"East Dennis, MA",
"McCook, NE",
"Somerset, PA",
"Nokomis, FL",
"Wheatland, WY",
"Franconia, VA",
"Fairfax Station, VA",
"Harlingen, TX",
"Angels Camp, CA",
"Newport, KY",
"Locust Grove, GA",
"Spring Park, MN",
"Shawnee, KS",
"Orrville, OH",
"Hickory Hills, IL",
"St Peters, MO",
"Birch Run, MI",
"Sedro-Woolley, WA",
"Blacksburg, SC",
"North Smithfield, RI",
"Greenwood, SC",
"Greater Harrisburg Area",
"Brookfield, WI",
"Wisconsin, United States",
"Clackamas, OR",
"Savage, MN",
"Prior Lake, MN",
"Benton, AR",
"Cottage Grove, OR",
"Meriden, CT",
"Los Lunas, NM",
"Rockford, IL",
"Elk Grove Village, IL",
"Torrington, CT",
"Soldotna, AK",
"Greenbrae, CA",
"Scarsdale, NY",
"Loves Park, IL",
"McPherson, KS",
"Lancaster, CA",
"New Britain, CT",
"Altoona, IA",
"Ankeny, IA",
"Little Elm, TX",
"Papillion, NE",
"North Conway, NH",
"Greater Fort Wayne",
"Middletown, CT",
"Lake Elmo, MN",
"Forest City, NC",
"Springfield, NE",
"New Prague, MN",
"Kenai, AK",
"Prineville, OR",
"Antioch, CA",
"Calexico, CA",
"Mill Valley, CA",
"Greater Syracuse-Auburn Area",
"Bethpage, NY",
"Flagstaff, AZ",
"Great Neck, NY",
"Marrero, LA",
"Tampa, Florida, United States",
"Evanston, IL",
"Algonquin, IL",
"Lake Villa, IL",
"Dartmouth, MA",
"Boston, Massachusetts, United States",
"Jackson, MI",
"Lititz, PA",
"Zachary, LA",
"Woodstock, GA",
"West Virginia, United States",
"West Jefferson, OH",
"El Monte, CA",
"Portland, TX",
"San Tan Valley, AZ",
"Wilmington, OH",
"Farmington, MI",
"Diamond Bar, CA",
"Lorton, VA",
"Ellisville, MO",
"Utica, NY",
"Pataskala, OH",
"Bloomingdale, GA",
"Grapevine, TX",
"Fort Huachuca, AZ",
"Yardley, PA",
"Wilmington, MA",
"Lawton, OK",
"Rockingham, NC",
"Midvale, UT",
"Richmond, TX",
"Pine Hall, NC",
"Aberdeen Proving Ground, MD",
"Norfolk County, MA",
"Morris, MN",
"Grafton, OH",
"Edinburgh, IN",
"Roanoke, TX",
"Watertown, MA",
"Avon, OH",
"Devens, MA",
"North Falmouth, MA",
"San Bruno, CA",
"Bernardsville, NJ",
"South Portland, ME",
"Latham, NY",
"West Covina, CA",
"Kenilworth, NJ",
"West New York, NJ",
"Prattville, AL",
"Quincy, IL",
"Newington, NH",
"Roseburg, OR",
"Suamico, WI",
"Antigo, WI",
"Salem, VA",
"Menomonie, WI",
"Joplin, MO",
"Inverness, FL",
"Derry, NH",
"Bridgeport, AL",
"Gary, IN",
"Hendersonville, TN",
"Brooksville, FL",
"Chaska, MN",
"Live Oak, TX",
"Tamarac, FL",
"Palatine, IL",
"Lawrenceburg, IN",
"Clifton, NJ",
"Bristol, PA",
"Allenwood, PA",
"Trinity, FL",
"Trenton, GA",
"Villa Park, IL",
"Sunrise, FL",
"Clarence, NY",
"Pearland, TX",
"Kenmore, NY",
"Shoemakersville, PA",
"Little Canada, MN",
"Saint Inigoes, MD",
"New Cumberland, PA",
"Atlantis, FL",
"Tarrytown, NY",
"Swansboro, NC",
"Forest Hill, MD",
"Blairsville, GA",
"Sinking Spring, PA",
"Ketchikan, AK",
"Vance, AL",
"Woodside, NY",
"Apache Junction, AZ",
"McChord Air Force Base, WA",
"Rolling Prairie, IN",
"Edgewood, MD",
"Elmira, NY",
"Painted Post, NY",
"Willmar, MN",
"New City, NY",
"Cookeville, TN",
"Union, KY",
"Willow Grove, PA",
"Manchester, IA",
"Bessemer, AL",
"Helena, MT",
"Maiden, NC",
"Harrisonburg, VA",
"Buffalo Grove, IL",
"Roanoke Rapids, NC",
"Ewa Gentry, HI",
"Londonderry, NH",
"Idaho, United States",
"Marshall, MI",
"Greater Bloomington, Illinois Area",
"Park City, KS",
"Caledonia, MI",
"Leesburg, FL",
"Santa Teresa, NM",
"Hanover, NH",
"Guilford, CT",
"Cheney, WA",
"Greater Bloomington Area",
"Geismar, LA",
"San Marcos, TX",
"Spring Hill, TN",
"Mercedes, TX",
"Oxford, OH",
"Central, SC",
"Wilsonville, OR",
"Cortland, NY",
"Pearl City, HI",
"La Grande, OR",
"Burien, WA",
"Anderson, SC",
"Romeo, MI",
"Travis Field, CA",
"West Fargo, ND",
"Fuquay-Varina, NC",
"Pasco, WA",
"Winter Garden, FL",
"Tullahoma, TN",
"San Carlos, CA",
"Wabash, IN",
"Hebron, KY",
"Merrimack County, NH",
"White Oak, NC",
"Pocasset, MA",
"Rockledge, FL",
"St Joseph, MI",
"Otsego, MN",
"El Dorado Hills, CA",
"Gainesville, GA",
"Sterling, VA",
"Ardmore, PA",
"Palmetto, GA",
"Madison, CT",
"Durham, CT",
"Cottonwood, AZ",
"Forest Lake, MN",
"Riverview, FL",
"Southington, CT",
"Brookings, SD",
"Victor, NY",
"Burlington, NJ",
"Berkeley, MO",
"Hackensack, NJ",
"Raynham, MA",
"Stuart, FL",
"Silicon Valley, CA",
"Chapin, SC",
"Dardanelle, AR",
"Hazlet, NJ",
"Kealakekua, HI",
"Greenbelt, MD",
"River Falls, WI",
"Cabazon, CA",
"Buckeye Lake, OH",
"Chisago City, MN",
"White City, OR",
"Townshend, VT",
"Chico, CA",
"Stone Mountain, GA",
"Deer Park, IL",
"Biscoe, NC",
"Conway, SC",
"Ingleside, TX",
"Johnstown, CO",
"Newport, OR",
"Sabine Pass, TX",
"Plaquemines Parish County, LA",
"Port Chester, NY",
"Woodbridge, VA",
"Bristol, IN",
"Apple Valley, MN",
"Oceanside, CA",
"Sycamore, IL",
"Loveland, CO",
"Richland County, SC",
"Marshfield, WI",
"Sandusky, OH",
"Bloomsburg, PA",
"Lewiston, ID",
"Nebraska City, NE",
"Lodi, CA",
"Millburn, NJ",
"Forest Home, NY",
"Shawano, WI",
"East Lansing, MI",
"Teterboro, NJ",
"Mayfield, OH",
"Jonesboro, AR",
"Tulare, CA",
"Truckee, CA",
"Ozark, AR",
"Carthage, MO",
"Coraopolis, PA",
"Lyons, NY",
"New Home, MO",
"Arcata, CA",
"Broken Arrow, OK",
"Harrison, NY",
"Smithfield, RI",
"Statesville, NC",
"Moore, OK",
"Tyler, TX",
"Toms River, NJ",
"Salinas, CA",
"Greater Wilmington Area",
"Andover, KS",
"Wilton Manors, FL",
"Tremont, PA",
"Port St Lucie, FL",
"Cedar Hill, TX",
"Hanover, PA",
"Mission Viejo, CA",
"Macomb, MI",
"Greenfield, MA",
"Great Barrington, MA",
"Commerce, CA",
"Gretna, NE",
"La Vergne, TN",
"Huntsville, AR",
"Hutchins, TX",
"Hope Mills, NC",
"Bolivar, MO",
"Fond du Lac, WI",
"Central Islip, NY",
"Pittsfield, MA",
"La Quinta, CA",
"Big Sky Meadow Village, MT",
"Bluffton, SC",
"Baraboo, WI",
"Lake St Louis, MO",
"Morristown, NJ",
"Freedom, CA",
"Sherwood, MI",
"Brighton, CO",
"Calistoga, CA",
"Loomis, CA",
"Garden City, MI",
"Petoskey, MI",
"Knoxville Metropolitan Area",
"Teton Village, WY",
"Taneytown, MD",
"Woodinville, WA",
"Dowagiac, MI",
"Clarion, PA",
"Big Rapids, MI",
"Harrisonville, MO",
"Montebello, CA",
"Minerva, OH",
"Centralia, WA",
"Ammon, ID",
"Clarksburg, WV",
"Eureka, CA",
"Belcamp, MD",
"Pueblo-Cañon City Area",
"Red Oak, TX",
"Perris, CA",
"Clinton, OK",
"Charlotte, AR",
"North Pole, AK",
"Cambridge, MN",
"Roswell, NM",
"Glenside, PA",
"Kalispell, MT",
"Leeds, NY",
"Adrian, MI",
"Delta, CO",
"Hodgkins, IL",
"Independence, KS",
"Killeen-Temple Area",
"Roxbury, ME",
"New Castle, PA",
"Goodwell, OK",
"Elizabethtown, PA",
"Mesa County, CO",
"Laconia, NH",
"Malta, OH",
"Euless, TX",
"Koloa, HI",
"Montevideo, MN",
"Hazel Crest, IL",
"Frenchtown, MI",
"Perham, MN",
"Fredonia, NY",
"Newnan, GA",
"Turlock, CA",
"Glassboro, NJ",
"Marquette, MI",
"West Point, PA",
"Jackson, GA",
"Spencer, IA",
"Fort Pierce, FL",
"Newport, RI",
"Bath, PA",
"Pinson, TN",
"New Port Richey, FL",
"Graham, NC",
"Fairfield, AL",
"Marion, SC",
"Somerville, NJ",
"Blue Bell, PA",
"Hatboro, PA",
"Montgomery, IL",
"Fernandina Beach, FL",
"Marlow Heights, MD",
"University, FL",
"Knox, IN",
"Cicero, NY",
"Honesdale, PA",
"Brunswick, GA",
"Seneca, SC",
"Del City, OK",
"Clinton, SC",
"Yakima, WA",
"Dallastown, PA",
"Simpsonville, SC",
"Orofino, ID",
"Travelers Rest, SC",
"Fleming Island, FL",
"Bridgeport, CT",
"Williamsport, PA",
"Liberty Lake, WA",
"Melrose Park, IL",
"Shingle Springs, CA",
"Zellwood, FL",
"Burns, OR",
"Defiance, OH",
"Hightstown, NJ",
"Poughkeepsie, NY",
"Hudson, MA",
"Kendall, FL",
"Winder, GA",
"Spartanburg County, SC",
"Brazil",
"Midlothian, VA",
"Kingston, NY",
"Big Spring, TX",
"Camden, SC",
"Mystic, CT",
"East Aurora, NY",
"Seminole, FL",
"Williamstown, MA",
"San Luis Obispo County, CA",
"Foster, RI",
"Leander, TX",
"Elkin, NC",
"Olympic Valley, CA",
"Belmont, WI",
"Indian Wells, CA",
"Pineville, LA",
"Barre, MA",
"Middletown, RI",
"Florham Park, NJ",
"Benson, AZ",
"Fairview, OR",
"Irmo, SC",
"Noblesville, IN",
"Bayonne, NJ",
"Solana Beach, CA",
"Union City, GA",
"Fairfield County, CT",
"Carlstadt, NJ",
"Whiting, IN",
"Gulfport, MS",
"West Point, GA",
"Port Washington, NY",
"Salt Lake County, UT",
"Vero Beach, FL",
"Orangeburg, NY",
"White Lake, MI",
"Yorkville, IL",
"Gray Court, SC",
"Lakeville, NY",
"Buffalo, WV",
"Rocky Hill, CT",
"Duncan, SC",
"Beatrice, NE",
"Elkhart County, IN",
"Ferndale, MI",
"Auburn, CA",
"Royal Oak, MI",
"Alcoa, TN",
"Cornelius, NC",
"Coos Bay, OR",
"Circle Pines, MN",
"Whitesboro, NY",
"Oklahoma County, OK",
"Laurinburg, NC",
"New Haven County, CT",
"Walterboro, SC",
"Millersville, MD",
"Lansdale, PA",
"San Fernando, CA",
"Columbine Valley, CO",
"Fairfield, NJ",
"Yucaipa, CA",
"Streetsboro, OH",
"Dacula, GA",
"Ruskin, FL",
"Hudson, NH",
"Corning, NY",
"Woodhull, IL",
"Lebanon, OH",
"Severna Park, MD",
"Monroe, CT",
"Solon, OH",
"Hudsonville, MI",
"South Burlington, VT",
"Jonestown, PA",
"Lakewood, NY",
"Skillman, NJ",
"Sun Prairie, WI",
"Coralville, IA",
"Ellsworth, IA",
"Fountain Inn, SC",
"Bartlett, IL",
"St John, IN",
"Brookhaven, GA",
"Altamonte Springs, FL",
"Haymarket, VA",
"Alamosa, CO",
"La Crosse, WI",
"Andover, MN",
"Toledo, Ohio Metropolitan Area",
"Trenton, SC",
"Rohnert Park, CA",
"Kennett Square, PA",
"Gulf Breeze, FL",
"Marin County, CA",
"Turners Falls, MA",
"Fort Mitchell, KY",
"Rockaway, NJ",
"Ashland, MA",
"Bridgeport, WV",
"Golden Valley, MN",
"Canonsburg, PA",
"Strongsville, OH",
"Brentwood, NY",
"Lugoff, SC",
"Saugus, MA",
"Centereach, NY",
"Mays Landing, NJ",
"East Northport, NY",
"Racine, WI",
"Radnor, PA",
"Clara City, MN",
"Compton, CA",
"Fairfax County, VA",
"Wheeling, IL",
"Ridgeway, SC",
"Lansing, NY",
"Streamwood, IL",
"Salem, NH",
"Granger, IN",
"Williamsville, NY",
"Dumfries, VA",
"New Hope, MN",
"Jamison, PA",
"Medina, OH",
"Newton, MA",
"Hegins, PA",
"Camp Lejeune, NC",
"El Granada, CA",
"Sparkill, NY",
"Rancho Palos Verdes, CA",
"Moorestown, NJ",
"Medina, MN",
"North Township, IN",
"Eagan, MN",
"Waller, TX",
"Portland, Maine Metropolitan Area",
"Harrington, DE",
"Linthicum, MD",
"Western, NY",
"Oberlin, OH",
"Alma, MI",
"Sammamish, WA",
"Magna, UT",
"Ronkonkoma, NY",
"Englishtown, NJ",
"Gates Mills, OH",
"Mason, MI",
"Superior, CO",
"West Deptford, NJ",
"Lathrop, CA",
"Rocky River, OH",
"Caruthersville, MO",
"Bear, DE",
"Panama City Beach, FL",
"Lumberton, NC",
"North Olmsted, OH",
"Park City, UT",
"Plainview, NY",
"Mehoopany, PA",
"Peapack - Gladstone, NJ",
"Davenport, FL",
"Alfred, NY",
"Springfield, Massachusetts Metropolitan Area",
"All, MO",
"Sheboygan Falls, WI",
"Chappaqua, NY",
"Corinne, UT",
"Ashland City, TN",
"Florence, AZ",
"Butler, PA",
"Boulder County, CO",
"West Lebanon, NH",
"Edgewater, NJ",
"Columbus, MS",
"Kendallville, IN",
"Montoursville, PA",
"Cameron, TX",
"Chicago Ridge, IL",
"Reading, MA",
"Smithfield, NC",
"Butner, NC",
"Greater Scranton Area",
"Edgartown, MA",
"Beech Island, SC",
"Jenks, OK",
"Healdsburg, CA",
"Colonial Heights, VA",
"North Palm Beach, FL",
"Loxley, AL",
"San Angelo Area",
"Columbia, TN",
"Greater Clarksville Area",
"Georgetown, KY",
"Greater Tuscaloosa Area",
"Prosper, TX",
"Canton, NC",
"Nicholasville, KY",
"Kutztown, PA",
"Milford, CT",
"Lady Lake, FL",
"Hyannis, MA",
"Hawthorne, NY",
"Mishawaka, IN",
"New Iberia, LA",
"Dutchess County, NY",
"Beeville, TX",
"Kaysville, UT",
"Madisonville, TN",
"Snellville, GA",
"Pennington, NJ",
"Whitmore Lake, MI",
"Mountain Home, ID",
"Tanner, AL",
"Natchez, MS",
"Greater Ocala Area",
"Littleton, NH",
"Upper St Clair, PA",
"Bridgeview, IL",
"Blue Ridge, VA",
"Palm Desert, CA",
"Genoa, OH",
"Pittsylvania County, VA",
"Bloomfield, CT",
"Marathon City, WI",
"Benson, MN",
"Downingtown, PA",
"Core, WV",
"Lincoln, CA",
"Universal City, CA",
"Auburn, GA",
"Newport News City County, VA",
"Owasso, OK",
"Fort Meade, Florida, United States",
"Greater Hattiesburg Area",
"Sayre, PA",
"Highland Park, TX",
"Kingston, MA",
"Halsey, OR",
"Astoria, OR",
"Chesterfield County, VA",
"Langley, SC",
"Westchester County, NY",
"Hialeah Gardens, FL",
"Florence, AL",
"Vidalia, GA",
"Liberty, SC",
"Melissa, TX",
"Memphis metropolitan area, MS",
"Burrillville, RI",
"Memphis Metropolitan Area",
"Damascus, MD",
"Fort Leonard Wood, MO",
"Buffalo, WY",
"Inwood, NY",
"Hartford City, IN",
"Dobbs Ferry, NY",
"Atascadero, CA",
"Clinton, MA",
"Lindon, UT",
"Virginia Beach City County, VA",
"Torrington, WY",
"New Smyrna Beach, FL",
"Corinth, MS",
"Creve Coeur, MO",
"Honolulu, Hawaii, United States",
"Highland, IL",
"Johns Island, SC",
"Crofton, MD",
"Covington, GA",
"East Hartford, CT",
"Yaphank, NY",
"Whippany, NJ",
"Brimfield, OH",
"Estero, FL",
"Mogadore, OH",
"Union, NJ",
"Bremen, IN",
"Palmdale, CA",
"Tysons Corner, VA",
"Black Mountain, NC",
"Dodgeville, WI",
"Wheaton, MD",
"Southampton, PA",
"Miramar Beach, FL",
"Summersville, WV",
"Princeton, WV",
"Potomac Mills, VA",
"Broussard, LA",
"Greater Tucson Area",
"Greenfield, IN",
"Watertown, WI",
"Hershey, PA",
"Middle Valley Estates, TN",
"Rapid City, MI",
"Irondale, AL",
"Whittier, CA",
"Moreno Valley, CA",
"Palisades Park, NJ",
"Willimantic, CT",
"Duncannon, PA",
"Bloomsbury, NJ",
"Mount Pleasant, PA",
"Benicia, CA",
"Strafford County, NH",
"Canyon, TX",
"Apple Valley, CA",
"Mason, OH",
"Douglas, GA",
"Malone, NY",
"Opelousas, LA",
"City Park, UT",
"Woodlawn, MD",
"Camp Hill, PA",
"Orem, UT",
"Norman, OK",
"Perrysburg, OH",
"Notre Dame, IN",
"Redwood Valley, CA",
"Avenel, NJ",
"Manlius, NY",
"Stafford, VA",
"Oakland, NJ",
"Old Chatham, NY",
"Artesia, MS",
"Crystal Springs, MS",
"Montrose, CO",
"Murrysville, PA",
"Farmington, UT",
"Galveston, TX",
"Carpinteria, CA",
"Mount Vernon, WA",
"Edgewood, NY",
"Zanesville, OH",
"Rio Rancho, NM",
"South El Monte, CA",
"Salisbury, NC",
"Lino Lakes, MN",
"Richfield, UT",
"Greater Morgantown Area",
"Mission, KS",
"Stonington, CT",
"Miller City, OH",
"Bay Minette, AL",
"Claremore, OK",
"Jonesville, MI",
"Delano, CA",
"Murrells Inlet, SC",
"West Palm Beach, Florida, United States",
"Eagle Mountain, UT",
"Leetonia, OH",
"Candler, NC",
"Nellis AFB, NV",
"Winfield, IL",
"Mount Vernon, NY",
"New Berlin, NY",
"Patterson, OH",
"Greencastle, IN",
"Ottawa, KS",
"Mayport, Florida, United States",
"Bettendorf, IA",
"Santee, CA",
"New Mexico, United States",
"Teaneck, NJ",
"Vicksburg, MS"]

company_location_list = ['California',
 'New Jersey',
 'Texas',
 'Georgia',
 'Florida',
 'TX',
 'New York',
 '0',
 'North Dakota',
 'GA',
 'CA',
 'MI',
 'Karnataka',
 'WA',
 'Washington',
 'England',
 'FL',
 'NC',
 'Ohio',
 'Illinois',
 'CALIFORNIA',
 'Montana',
 'NY',
 'PA',
 'Virginia',
 'Colorado',
 'IL',
 'MO',
 'Maryland',
 'AK',
 'Indiana',
 'South Carolina',
 'iowa',
 'AZ',
 'SC',
 'British Columbia',
 'Arizona',
 'District of Columbia',
 'Connecticut',
 'Massachusetts',
 'Alabama',
 'Dubai',
 'Minnesota',
 'Madrid',
 'ID',
 'Oklahoma',
 'OH',
 'UT',
 'Missouri',
 'Wisconsin',
 'Iowa',
 'VA',
 'Tennessee',
 'MD',
 'DC',
 'MA',
 'OK',
 'WY',
 'MN',
 'TN',
 'New Hampshire',
 'Kentucky',
 'Pennsylvania',
 'CT',
 'Rhode Island',
 'PA ',
 'New York ',
 'WI',
 'NJ',
 'Saskatchewan',
 'KARNATAKA',
 'Queensland',
 'South Dakota',
 'NSW',
 'Utah',
 'Nebraska',
 'Michigan',
 'FLORIDA',
 'CO',
 'Idaho',
 'Herts',
 'Maine',
 'Ontario',
 'KS',
 'North Carolina',
 'Barcelona',
 'East Sussex',
 'Maharashtra',
 'Scotland',
 'ENGLAND',
 'IN',
 'France',
 'Wyoming',
 'Nevada',
 'MS',
 'Delaware',
 'NewJersey',
 'tx',
 'Telangana',
 'Az',
 'ME',
 'Weybridge',
 'NV',
 'Gujarat',
 'Bedfordshire',
 'ND',
 'Utrecht',
 'AL',
 'IA',
 'Berlin',
 'London',
 'Geneva',
 'Kerala',
 'OR',
 'WY ',
 'DE',
 'Oregon',
 'Texas ',
 'Kansas',
 'New Jersey ',
 'Skane County',
 'Hawaii',
 'Switzerland',
 'Mississippi',
 'NH',
 'Iceland',
 'LA',
 'Hong Kong',
 'Harayana ',
 'MH',
 'St. Gallen',
 'Zurich',
 'Uttar Pradesh',
 'Georgia (GA)',
 'Tamil Nadu',
 'NE',
 'North Carolina ',
 'Tokyo',
 'BC',
 'New Mexico',
 'Greater London',
 'Arkansas',
 'AR',
 'maryland',
 'NM',
 'CT ',
 'TEXAS',
 'Quebec',
 'HI',
 'ct',
 'Dublin',
 'Hessen',
 'SD',
 ' MA ',
 'Spain',
 'Alberta',
 'KY',
 'North Holland',
 'Shanghai',
 'California ',
 'DELAWARE (DE)',
 'Changzhou',
 'Ireland',
 'VT',
 'Tamilnadu',
 'Finland',
 'Louisiana',
 'CA - California',
 'Bucks',
 'Community of Madrid',
 'USA',
 'Sweden',
 'CH',
 'Pennsylvania ',
 'D.C.',
 'Seoul',
 'Bayern',
 'Rogaland',
 'N.J.',
 'Walloon Region',
 'Ca',
 'Nordrhein-Westfalen',
 'New Taipei City',
 'Bay of Plenty',
 'QC',
 'MT',
 'Tx',
 'Florence',
 'MICHIGAN',
 'Taguig',
 'Co',
 'Gloucestershire',
 'co',
 'MA ',
 'CO.',
 'Wa',
 'wa',
 'Middlesex',
 'Louisiana ',
 'Stockholm',
 'Ile-de-France',
 'Strand',
 'il',
 'Frankfurt',
 'Île-de-France',
 'Berkshire',
 'Western Australia',
 'ca',
 'Ma',
 'Washington ',
 'Mi',
 'ZG',
 'Córdoba',
 'wi',
 'Victoria',
 'Alaska',
 'Vienna',
 'Sp',
 'Guangdong',
 'AB',
 'Prague',
 '28801',
 'Singapore',
 'Kanagawa ',
 'Baselstadt',
 'Il',
 'Illinois ',
 'Jalisco',
 'Anywhere',
 'mi',
 'Jiangsu',
 'WA ',
 'Taiwan',
 'Auckland',
 '東京都',
 'Israel',
 'Huangpu',
 'QLD',
 'Haryana',
 'FI',
 'Abu Dhabi',
 '广东省',
 'Uusimaa',
 'NRW',
 'buenos aires',
 'Styria',
 'Lincolnwood, Illinois',
 'UP',
 'RI',
 'North Rhine-Westphalia ',
 'Georgia ',
 'Wi',
 'ON',
 'Cambridgeshire',
 'ga',
 'NY ',
 'BW',
 'Bavaria',
 'Luton',
 'United States',
 'Auvergne-Rhône-Alpes',
 'Washington D.C.',
 'North Rhine-Westphalia',
 'Valby',
 'New South Wales',
 'ONTARIO',
 'VIC',
 'South Holland',
 'Paris',
 'Zürich',
 'Sussex',
 'Manitoba',
 'CA.',
 'BS',
 'Skane',
 'Zuid-Holland',
 'Gyeonggi-do',
 'Parma',
 'treinta y tres',
 'WV',
 'Fl',
 'China',
 'Cheshire',
 'Hampshire',
 'Central London ',
 'Baden-Württemberg',
 'FL ',
 'Québec',
 'Vermont',
 'Ile de France',
 'Antrim',
 'Al',
 'Surrey',
 'North-Rhine-Westphalia',
 'Bermuda',
 'VA ',
 'Calif.',
 'SK',
 'Pa',
 '01824',
 'NY - New York',
 'Noord-Holland',
 'Italia',
 'Stockholm County',
 'md',
 'Cambs',
 'Osaka',
 'Ilinois',
 'West Midlands',
 'fl',
 'Delhi',
 '94086',
 'ma',
 'Maharastra',
 'GA ',
 'In',
 'Basel-Country',
 'Hertfordshire',
 'TX ',
 'Yvelines',
 'Helsinki',
 'GEORGIA',
 'Hrvatska',
 'Nuevo León',
 'Occitanie',
 'TENNESSEE',
 'Zug',
 'Minnesota ',
 'Hamburg']

job_benefits = ['Medical insurance',
 'None',
 '401(k)',
 'Disability insurance',
 'Vision insurance',
 'Dental insurance',
 'Paid paternity leave',
 'Pension plan',
 'Tuition assistance',
 'Commuter benefits',
 'Paid maternity leave',
 'Child care support',
 'Student loan assistance']

company_countries = ['US',
 'IN',
 'GB',
 'CA',
 'AE',
 'IE',
 'ES',
 'MD',
 'FI',
 'AU',
 'FR',
 'DK',
 'NL',
 'DE',
 'CH',
 'KR',
 'SE',
 'IS',
 'HK',
 'JP',
 'BE',
 'CN',
 'IL',
 'SG',
 'OO',
 'NO',
 'TW',
 'NZ',
 'IT',
 'PH',
 'MX',
 'ID',
 'LU',
 'AT',
 'AR',
 'VN',
 'BR',
 'CZ',
 'PR',
 'CO',
 'KY',
 'UY',
 'HU',
 'SA',
 'GE',
 'TR',
 'BM',
 'KE',
 'HR']

job_skill_types = ['SALE',
 'ACCT',
 'DSGN',
 'ADM',
 'EDU',
 'ENG',
 'HCPR',
 'OTHR',
 'PRJM',
 'FIN',
 'HR',
 'MGMT',
 'MRKT',
 'IT',
 'GENB',
 'BD',
 'LGL',
 'CUST',
 'QA',
 'PRDM',
 'CNSL',
 'RSCH',
 'MNFC',
 'STRA',
 'ART',
 'ANLS',
 'PRCH',
 'SUPL',
 'DIST',
 'SCI',
 'PROD',
 'PR',
 'WRT',
 'TRNG',
 'ADVR']

company_industries = ['Transportation/Trucking/Railroad',
 'Staffing & Recruiting',
 'Religious Institutions',
 'Design',
 'Retail',
 'Computer Software',
 'Architecture & Planning',
 'Fine Art',
 'Construction',
 'Hospital & Health Care',
 'Real Estate',
 'Automotive',
 'Restaurants',
 'Information Technology & Services',
 'Media Production',
 'Higher Education',
 'Printing',
 'Consumer Goods',
 'Mental Health Care',
 'Environmental Services',
 'Health, Wellness & Fitness',
 'Law Practice',
 'Mechanical Or Industrial Engineering',
 'Non-profit Organization Management',
 'Facilities Services',
 'Medical Device',
 'Marketing & Advertising',
 'Banking',
 'Hospitality',
 'Government Administration',
 'Aviation & Aerospace',
 'Security & Investigations',
 'Civic & Social Organization',
 'Apparel & Fashion',
 'Furniture',
 'Entertainment',
 'Cosmetics',
 'Insurance',
 'Research',
 'International Trade & Development',
 'Veterinary',
 'Food & Beverages',
 'Mining & Metals',
 'Human Resources',
 'Utilities',
 'Farming',
 'Information Services',
 'Events Services',
 'Education Management',
 'Consumer Services',
 'Biotechnology',
 'Airlines/Aviation',
 'Financial Services',
 'Medical Practice',
 'Oil & Energy',
 'Accounting',
 'Legal Services',
 'Defense & Space',
 'Individual & Family Services',
 'Electrical & Electronic Manufacturing',
 'Pharmaceuticals',
 'Plastics',
 'Building Materials',
 'Public Safety',
 'Chemicals',
 'Management Consulting',
 'Wholesale',
 'Graphic Design',
 'Packaging & Containers',
 'Logistics & Supply Chain',
 'Recreational Facilities & Services',
 'Internet',
 'Civil Engineering',
 'Outsourcing/Offshoring',
 'Public Relations & Communications',
 'Telecommunications',
 'Primary/Secondary Education',
 'Newspapers',
 'Broadcast Media',
 'Food Production',
 'Computer Games',
 'Semiconductors',
 'Consumer Electronics',
 'Government Relations',
 'Machinery',
 'Leisure, Travel & Tourism',
 'Market Research',
 'Performing Arts',
 'Maritime',
 'Political Organization',
 'Venture Capital & Private Equity',
 'Fundraising',
 'Industrial Automation',
 'Sports',
 'Investment Management',
 'Writing & Editing',
 'Investment Banking',
 'Military',
 'Paper & Forest Products',
 'Luxury Goods & Jewelry',
 'Capital Markets',
 'Alternative Medicine',
 'Law Enforcement',
 'Wine & Spirits',
 'Gambling & Casinos',
 'E-learning',
 'Glass, Ceramics & Concrete',
 'Renewables & Environment',
 'Dairy',
 'Online Media',
 'Commercial Real Estate',
 'Computer & Network Security',
 'Music',
 'Translation & Localization',
 'Museums & Institutions',
 'Computer Hardware',
 'Professional Training & Coaching',
 'Publishing',
 'Photography',
 'Philanthropy',
 'Sporting Goods',
 'Think Tanks',
 'Judiciary',
 'Package/Freight Delivery',
 'Railroad Manufacture',
 'Textiles',
 'Business Supplies & Equipment',
 'Tobacco',
 'Supermarkets',
 'International Affairs',
 'Computer Networking',
 'Warehousing',
 'Executive Office',
 'Import & Export',
 'Animation',
 'Shipbuilding',
 'Public Policy',
 'Legislative Office',
 'Libraries',
 'Wireless',
 'Fishery']

def validate_and_convert_data(data, data_types):
    validated_data = {}

    for key, value in data.items():
        if key in data_types:
            dtype_str = data_types[key]
            dtype_str = dtype_str.replace("dtype('", "").replace("')", "")  # Extract the dtype string

            # Convert the value to the specified dtype
            if dtype_str.startswith('int'):
                validated_data[key] = int(value)
            elif dtype_str.startswith('float'):
                validated_data[key] = float(value)
            else:
                # Convert to 'object' dtype
                validated_data[key] = str(value)
        else:
            # If the key is not in data_types, convert to 'object' dtype
            validated_data[key] = str(value)

    return validated_data

data_types = {
    "job_id": "dtype('int64')",
    "company_id": "dtype('int64')",
    "title": "dtype('O')",
    "job_desc": "dtype('O')",
    "formatted_work_type": "dtype('O')",
    "location": "dtype('O')",
    "applies": "dtype('int64')",
    "views": "dtype('int64')",
    "application_type": "dtype('O')",
    "formatted_experience_level": "dtype('O')",
    "sponsored": "dtype('int64')",
    "company_name": "dtype('O')",
    "company_desc": "dtype('O')",
    "company_size": "dtype('float64')",
    "company_state": "dtype('O')",
    "company_country": "dtype('O')",
    "company_city": "dtype('O')",
    "company_zip_code": "dtype('O')",
    "company_address": "dtype('O')",
    "job_benefit": "dtype('O')",
    "job_skill_type": "dtype('O')",
    "company's roles": "dtype('O')",
    "company's industry": "dtype('O')"
}